version: '3.7'

services:
  app:
    build: .
    restart: always
    ports:
      - '8000:80'
    volumes:
      - './:/var/www/html'
    networks:
      - default
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

volumes:
  postgres_data: